# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
    - uses: pdm-project/setup-pdm@v3.3
      with:
        python-version: 3.11
        cache: true
      
    - name: Install dependencies
      run: |
        pdm venv create --with-pip --force $PYTHON
        pdm install
    - name: Lint with ruff
      run: |
        ruff .
    - name: Test with pytest
      run: |
        pdm run pytest
